#+TITLE: Rostrum 2
#+SUBTITLE: Worship service program generator and manager

A web application to manage the creation and publication of programs for religious services, like those of the weekly Sunday services held by the [[https://churchofjesuschrist.org][Church of Jesus Christ of Latter-day Saints]].

* Synopsis

This project is built using the [[https://phoenixframework.org/][Phoenix web framework]] built on top of [[https://elixir-lang.org][Elixir]].

 - Install dependencies with ~mix deps.get~
 - Start up db with ~mix docker.db start~
 - Create database with ~mix ecto.setup~
 - Start Phoenix as server with ~mix phx.server~ or inside an IEx shell with ~iex -S mix phx.server~

Project should be running at [[http://localhost:4000]].

* Description

Online bulletins are all the rage now: they're more convenient, not to mention better for our health (no COVID, please) and the environment. Sharing a link to a read-only version of a Google Doc is kinda… well… sub-optimal. Let's make something that is both easy to use and really pretty to look at.

** Goals

 - Web-first: I'll be skipping the PDF generation and focusing on having a nice, easy-to-read web version.
 - Flexible: I won't take too much structure into the programs this time.
 - Multi-account: we'll bake accounts into the project from the beginning.

** Stack

 - Postgres
 - Elixir
 - Phoenix
 - LiveView
 - Tailwind
 - Alpine.js?

** Road map [1/4]

 - [X] Authentication
 - [ ] Program builder interface
 - [ ] Public, non-authenticated render
 - [ ] QR code generation

* Contributing

Contributions welcome!

When you open a PR, please include a descriptive PR write-up (it doesn't have to be a dissertation, but it should explain well what the purpose of the PR is) and include some tests to validate your changes.

Be kind. This is a hobby project being run by a very busy college student.

* License and disclaimer

MIT License

This work is not endorsed by the [[https://churchofjesuschrist.org/][Church of Jesus Christ of Latter-day Saints]] or any of its representatives. It is simply modeled after the needs of a typical Sunday worship service. You may use this software for anything you like.

* Authors

 - [[https://github.com/ashton314][Ashton Wiersdorf]]
